name: Deploy app on Airbase

on: push

jobs:
  Airbase-Deploy-Prod:
    if: github.ref_name == 'main'
    runs-on: ubuntu-24.04
    environment: prod  
    container:
      image: gdssingapore/airbase:cli
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Airbase Build
        run: airbase container build

      - name: Airbase Deploy
        shell: bash
        run: |
          echo "${{ secrets.AIRBASE_RC }}" > ~/.airbaserc
          echo "${{ secrets.AIRBASE_ENV_LOCAL_FILE }}" > .env.local

          airbase container deploy --output deploy.env --yes --project "${{ secrets.AIRBASE_PROJECT_HANDLE }}" uat
          source deploy.env
          echo "PROD app is deployed successfully! Visit [$DYNAMIC_ENVIRONMENT_URL]($DYNAMIC_ENVIRONMENT_URL) to view your app." >> $GITHUB_STEP_SUMMARY

  Airbase-Deploy-UAT:
    if: github.ref_name == 'uat'
    runs-on: ubuntu-24.04
    environment: uat 
    container:
      image: gdssingapore/airbase:cli
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Airbase Build
        run: airbase container build

      - name: Airbase Deploy
        shell: bash
        run: |
          echo "${{ secrets.AIRBASE_RC }}" > ~/.airbaserc
          echo "${{ vars.AIRBASE_ENV_LOCAL_FILE }}" > .env.local

          airbase container deploy --output deploy.env --yes --project "${{ secrets.AIRBASE_PROJECT_HANDLE }}" abc
          source deploy.env
          echo "UAT app is deployed successfully! Visit [$DYNAMIC_ENVIRONMENT_URL]($DYNAMIC_ENVIRONMENT_URL) to view your app." >> $GITHUB_STEP_SUMMARY
